image: Visual Studio 2017
init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
install:
  - git submodule update --init --recursive
build_script:
  - msbuild annonet_cpu.sln /t:test\annonet_test_cpu:rebuild /p:DefineConstants=DLIB_DNN_PIMPL_WRAPPER_LEVEL_COUNT=0 /p:Platform=x64 /p:Configuration=Release
  - msbuild annonet_cpu.sln /t:test\annonet_test_cpu:rebuild /p:DefineConstants=DLIB_DNN_PIMPL_WRAPPER_LEVEL_COUNT=0 /p:Platform=x64 /p:Configuration=ReleaseGrayscaleInput
  - x64\Release\annonet_test_cpu.exe
  - x64\ReleaseGrayscaleInput\annonet_test_cpu.exe
  - msbuild annonet_cpu.sln /t:test\annonet_test_cpu:rebuild /p:DefineConstants=DLIB_DNN_PIMPL_WRAPPER_LEVEL_COUNT=1 /p:Platform=x64 /p:Configuration=Release
  - msbuild annonet_cpu.sln /t:test\annonet_test_cpu:rebuild /p:DefineConstants=DLIB_DNN_PIMPL_WRAPPER_LEVEL_COUNT=1 /p:Platform=x64 /p:Configuration=ReleaseGrayscaleInput
  - x64\Release\annonet_test_cpu.exe
  - x64\ReleaseGrayscaleInput\annonet_test_cpu.exe
  - msbuild annonet_cpu.sln /t:test\annonet_test_cpu:rebuild /p:DefineConstants=DLIB_DNN_PIMPL_WRAPPER_LEVEL_COUNT=2 /p:Platform=x64 /p:Configuration=Release
  - msbuild annonet_cpu.sln /t:test\annonet_test_cpu:rebuild /p:DefineConstants=DLIB_DNN_PIMPL_WRAPPER_LEVEL_COUNT=2 /p:Platform=x64 /p:Configuration=ReleaseGrayscaleInput
  - x64\Release\annonet_test_cpu.exe
  - x64\ReleaseGrayscaleInput\annonet_test_cpu.exe
  - msbuild annonet_cpu.sln /t:test\annonet_test_cpu:rebuild /p:DefineConstants=DLIB_DNN_PIMPL_WRAPPER_LEVEL_COUNT=3 /p:Platform=x64 /p:Configuration=Release
  - msbuild annonet_cpu.sln /t:test\annonet_test_cpu:rebuild /p:DefineConstants=DLIB_DNN_PIMPL_WRAPPER_LEVEL_COUNT=3 /p:Platform=x64 /p:Configuration=ReleaseGrayscaleInput
  - x64\Release\annonet_test_cpu.exe
  - x64\ReleaseGrayscaleInput\annonet_test_cpu.exe
  - msbuild annonet_cpu.sln /t:test\annonet_test_cpu:rebuild /p:DefineConstants=DLIB_DNN_PIMPL_WRAPPER_LEVEL_COUNT=4 /p:Platform=x64 /p:Configuration=Release
  - msbuild annonet_cpu.sln /t:test\annonet_test_cpu:rebuild /p:DefineConstants=DLIB_DNN_PIMPL_WRAPPER_LEVEL_COUNT=4 /p:Platform=x64 /p:Configuration=ReleaseGrayscaleInput
  - x64\Release\annonet_test_cpu.exe
  - x64\ReleaseGrayscaleInput\annonet_test_cpu.exe
