image: Visual Studio 2017
init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
install:
  - git submodule update --init --recursive
build_script:
  - msbuild annonet_cpu.sln /p:Configuration=Release /p:Platform=x64
